### ISSUE TITLE
Chess history variants documentation

### ISSUE THREAD

**Issue by Woosy** [shaack/cm-chess#1]
Hello!

I've been playing with your `cm-chessboard` library for a week in a Nuxt.js project (after trying a few other chessboard libraries), and I really enjoy it.

I saw that you also made `cm-chess` based on chess.js (which I am using now), so I'm considering switching to `cm-chess` because of the "chess history variants" feature.
However, I am not familiar with chess programming and chess libraries, so I don't know how to use it.
I was wondering if you could write and/or point me to some documentation about this feature.

Thank you for your work, I really enjoy it.

**Comment by shaack** [comment]
Hi, thanks! cm-chess is a kind of merge between chess.js and [cm-pgn](https://github.com/shaack/cm-pgn). chess.js does the move validation and cm-pgn does the data storage. So if you call `chess.history()` in `cm-chess` you will get the data structure from `cm-pgn.history.moves`, as described in the README of [cm-pgn](https://github.com/shaack/cm-pgn).

The moves of the main variant are similar to the history array of chess.js. But in **cm-chess** you have the additional attributes "previous", "next" and "variations", which point to the previous move, the next move and optional to another array, where the variations of that move are stored.

I hope I was able to create some clarity with this, otherwise, just ask again.
